#############################################################################
# Makefile for building: SuperLooper
# Generated by qmake (2.01a) (Qt 4.7.4) on: Fri Oct 31 21:18:56 2014
# Project:  SuperLooper.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.7.4/bin/qmake -o Makefile SuperLooper.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++-64 -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include -I. -Igui -Isettings -Ilooper -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.7.4/lib -lQtGui -L/usr/local/Trolltech/Qt-4.7.4/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.7.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		gui/AboutDialog.cpp \
		gui/FrameEditWidget.cpp \
		gui/FrameSizeEditWidget.cpp \
		gui/FrameStartTimeEditWidget.cpp \
		gui/LicenseDialog.cpp \
		gui/LooperDialog.cpp \
		gui/SpeedEditWidget.cpp \
		looper/Looper.cpp \
		looper/MediaInfo.cpp \
		settings/LooperSettings.cpp \
		settings/MPlayerOptionsManager.cpp moc_AboutDialog.cpp \
		moc_FrameEditWidget.cpp \
		moc_FrameSizeEditWidget.cpp \
		moc_FrameStartTimeEditWidget.cpp \
		moc_LicenseDialog.cpp \
		moc_LooperDialog.cpp \
		moc_SpeedEditWidget.cpp \
		moc_Looper.cpp \
		moc_MediaInfo.cpp \
		moc_LooperSettings.cpp
OBJECTS       = main.o \
		AboutDialog.o \
		FrameEditWidget.o \
		FrameSizeEditWidget.o \
		FrameStartTimeEditWidget.o \
		LicenseDialog.o \
		LooperDialog.o \
		SpeedEditWidget.o \
		Looper.o \
		MediaInfo.o \
		LooperSettings.o \
		MPlayerOptionsManager.o \
		moc_AboutDialog.o \
		moc_FrameEditWidget.o \
		moc_FrameSizeEditWidget.o \
		moc_FrameStartTimeEditWidget.o \
		moc_LicenseDialog.o \
		moc_LooperDialog.o \
		moc_SpeedEditWidget.o \
		moc_Looper.o \
		moc_MediaInfo.o \
		moc_LooperSettings.o
DIST          = /usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf \
		SuperLooper.pro
QMAKE_TARGET  = SuperLooper
DESTDIR       = 
TARGET        = SuperLooper

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SuperLooper.pro  /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtCore.prl
	$(QMAKE) -o Makefile SuperLooper.pro
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile SuperLooper.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SuperLooper1.0.0 || $(MKDIR) .tmp/SuperLooper1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SuperLooper1.0.0/ && $(COPY_FILE) --parents gui/AboutDialog.h gui/FrameEditWidget.h gui/FrameSizeEditWidget.h gui/FrameStartTimeEditWidget.h gui/LicenseDialog.h gui/LooperDialog.h gui/SpeedEditWidget.h looper/Looper.h looper/MediaInfo.h settings/LooperSettings.h settings/MPlayerOptionsManager.h .tmp/SuperLooper1.0.0/ && $(COPY_FILE) --parents main.cpp gui/AboutDialog.cpp gui/FrameEditWidget.cpp gui/FrameSizeEditWidget.cpp gui/FrameStartTimeEditWidget.cpp gui/LicenseDialog.cpp gui/LooperDialog.cpp gui/SpeedEditWidget.cpp looper/Looper.cpp looper/MediaInfo.cpp settings/LooperSettings.cpp settings/MPlayerOptionsManager.cpp .tmp/SuperLooper1.0.0/ && (cd `dirname .tmp/SuperLooper1.0.0` && $(TAR) SuperLooper1.0.0.tar SuperLooper1.0.0 && $(COMPRESS) SuperLooper1.0.0.tar) && $(MOVE) `dirname .tmp/SuperLooper1.0.0`/SuperLooper1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SuperLooper1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_AboutDialog.cpp moc_FrameEditWidget.cpp moc_FrameSizeEditWidget.cpp moc_FrameStartTimeEditWidget.cpp moc_LicenseDialog.cpp moc_LooperDialog.cpp moc_SpeedEditWidget.cpp moc_Looper.cpp moc_MediaInfo.cpp moc_LooperSettings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AboutDialog.cpp moc_FrameEditWidget.cpp moc_FrameSizeEditWidget.cpp moc_FrameStartTimeEditWidget.cpp moc_LicenseDialog.cpp moc_LooperDialog.cpp moc_SpeedEditWidget.cpp moc_Looper.cpp moc_MediaInfo.cpp moc_LooperSettings.cpp
moc_AboutDialog.cpp: gui/LicenseDialog.h \
		gui/AboutDialog.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) gui/AboutDialog.h -o moc_AboutDialog.cpp

moc_FrameEditWidget.cpp: gui/FrameSizeEditWidget.h \
		gui/FrameStartTimeEditWidget.h \
		gui/FrameEditWidget.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) gui/FrameEditWidget.h -o moc_FrameEditWidget.cpp

moc_FrameSizeEditWidget.cpp: gui/FrameSizeEditWidget.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) gui/FrameSizeEditWidget.h -o moc_FrameSizeEditWidget.cpp

moc_FrameStartTimeEditWidget.cpp: gui/FrameStartTimeEditWidget.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) gui/FrameStartTimeEditWidget.h -o moc_FrameStartTimeEditWidget.cpp

moc_LicenseDialog.cpp: gui/LicenseDialog.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) gui/LicenseDialog.h -o moc_LicenseDialog.cpp

moc_LooperDialog.cpp: gui/FrameEditWidget.h \
		gui/FrameSizeEditWidget.h \
		gui/FrameStartTimeEditWidget.h \
		gui/SpeedEditWidget.h \
		settings/LooperSettings.h \
		looper/Looper.h \
		looper/MediaInfo.h \
		settings/MPlayerOptionsManager.h \
		gui/AboutDialog.h \
		gui/LicenseDialog.h \
		gui/LooperDialog.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) gui/LooperDialog.h -o moc_LooperDialog.cpp

moc_SpeedEditWidget.cpp: gui/SpeedEditWidget.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) gui/SpeedEditWidget.h -o moc_SpeedEditWidget.cpp

moc_Looper.cpp: looper/Looper.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) looper/Looper.h -o moc_Looper.cpp

moc_MediaInfo.cpp: looper/MediaInfo.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) looper/MediaInfo.h -o moc_MediaInfo.cpp

moc_LooperSettings.cpp: settings/LooperSettings.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) settings/LooperSettings.h -o moc_LooperSettings.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp gui/LooperDialog.h \
		gui/FrameEditWidget.h \
		gui/FrameSizeEditWidget.h \
		gui/FrameStartTimeEditWidget.h \
		gui/SpeedEditWidget.h \
		settings/LooperSettings.h \
		looper/Looper.h \
		looper/MediaInfo.h \
		settings/MPlayerOptionsManager.h \
		gui/AboutDialog.h \
		gui/LicenseDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

AboutDialog.o: gui/AboutDialog.cpp gui/AboutDialog.h \
		gui/LicenseDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AboutDialog.o gui/AboutDialog.cpp

FrameEditWidget.o: gui/FrameEditWidget.cpp gui/FrameEditWidget.h \
		gui/FrameSizeEditWidget.h \
		gui/FrameStartTimeEditWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FrameEditWidget.o gui/FrameEditWidget.cpp

FrameSizeEditWidget.o: gui/FrameSizeEditWidget.cpp gui/FrameSizeEditWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FrameSizeEditWidget.o gui/FrameSizeEditWidget.cpp

FrameStartTimeEditWidget.o: gui/FrameStartTimeEditWidget.cpp gui/FrameStartTimeEditWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FrameStartTimeEditWidget.o gui/FrameStartTimeEditWidget.cpp

LicenseDialog.o: gui/LicenseDialog.cpp gui/LicenseDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LicenseDialog.o gui/LicenseDialog.cpp

LooperDialog.o: gui/LooperDialog.cpp gui/LooperDialog.h \
		gui/FrameEditWidget.h \
		gui/FrameSizeEditWidget.h \
		gui/FrameStartTimeEditWidget.h \
		gui/SpeedEditWidget.h \
		settings/LooperSettings.h \
		looper/Looper.h \
		looper/MediaInfo.h \
		settings/MPlayerOptionsManager.h \
		gui/AboutDialog.h \
		gui/LicenseDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LooperDialog.o gui/LooperDialog.cpp

SpeedEditWidget.o: gui/SpeedEditWidget.cpp gui/SpeedEditWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpeedEditWidget.o gui/SpeedEditWidget.cpp

Looper.o: looper/Looper.cpp looper/Looper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Looper.o looper/Looper.cpp

MediaInfo.o: looper/MediaInfo.cpp looper/MediaInfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MediaInfo.o looper/MediaInfo.cpp

LooperSettings.o: settings/LooperSettings.cpp settings/LooperSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LooperSettings.o settings/LooperSettings.cpp

MPlayerOptionsManager.o: settings/MPlayerOptionsManager.cpp settings/MPlayerOptionsManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MPlayerOptionsManager.o settings/MPlayerOptionsManager.cpp

moc_AboutDialog.o: moc_AboutDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AboutDialog.o moc_AboutDialog.cpp

moc_FrameEditWidget.o: moc_FrameEditWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FrameEditWidget.o moc_FrameEditWidget.cpp

moc_FrameSizeEditWidget.o: moc_FrameSizeEditWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FrameSizeEditWidget.o moc_FrameSizeEditWidget.cpp

moc_FrameStartTimeEditWidget.o: moc_FrameStartTimeEditWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FrameStartTimeEditWidget.o moc_FrameStartTimeEditWidget.cpp

moc_LicenseDialog.o: moc_LicenseDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LicenseDialog.o moc_LicenseDialog.cpp

moc_LooperDialog.o: moc_LooperDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LooperDialog.o moc_LooperDialog.cpp

moc_SpeedEditWidget.o: moc_SpeedEditWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SpeedEditWidget.o moc_SpeedEditWidget.cpp

moc_Looper.o: moc_Looper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Looper.o moc_Looper.cpp

moc_MediaInfo.o: moc_MediaInfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MediaInfo.o moc_MediaInfo.cpp

moc_LooperSettings.o: moc_LooperSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LooperSettings.o moc_LooperSettings.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

